# ---------------------------------------------------
#             Sonus - Main Configuration
# ---------------------------------------------------

general:
  # Enable detailed debug messages in the server console.
  debug-mode: false # [Default: false]

  # Enables checking for newer versions of the plugin
  check-for-updates: true # [Default: true]